steebie/steebie/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.decorators import user_passes_test, login_required
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from campaigns.urls import (
    api_products_patterns,
    api_orders_patterns,
)
from base.views import RobotsView
from customers.urls import webhooks_customers

# API

api_patterns = [
    re_path('public/?', include(public_api_patterns)),
    re_path('products[/]?', include(api_products_patterns)),
    re_path('orders[/]?', include(api_orders_patterns)),
]

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('robots.txt', RobotsView.as_view()),
    path(
        'app',
        login_required()(
            user_passes_test(lambda u: u.is_merchant)(TemplateView.as_view(template_name='merchant/home.html'))
        ),
        name='app'
    ),
    path(settings.ADMIN_URL, admin.site.urls),
    path('account/', include(('users.urls', 'users'), namespace='users')),
    # API
    path('api/v1/', include((api_patterns, 'api'), namespace='v1')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

steebie/users/urls.py
from django.urls import path

from .views import UserDetailView

urlpatterns = [
    path('', view=UserDetailView.as_view(), name='account'),
]

steebie/base/models/shopify.py
from decimal import Decimal
import datetime
import time

from django.db import models

from shopify import Metafield

from base.exceptions import ShopifyApiError
from utils.shopify import set_shopify_site


class BaseShopify(models.Model):
    """Base model for Shopify data"""

    # List of Shopify attributes
    shopify_fields = []

    # Map: Shopify attributes names -> model attributes names (if differ)
    # E.g. you have model field shopify_id that represents Shopify id attribute, add it like that:
    # {'id': 'shopify_id'}
    shopify_fields_map = {}

    # Shopify resource class
    # E.g. shopify.Product
    shopify_resource_cls = None

    # Nested models names
    shopify_nested = []
    # Field holds parent object
    shopify_parent = None
    # Field holds Shopify parent object
    shopify_parent_id_name = None

    metafields_namespace = 'steebie'

    @classmethod
    def get_shopify_fields(cls):
        """Returns Shopify -> Model fields names mapping (key is Shopify name, value is model name)

        Returns:
            dict[str, str]
        """
        names = {k: k for k in cls.shopify_fields}
        names.update(**cls.shopify_fields_map)
        return names

    def get_shopify_id(self):
        """Returns Shopify ID

        Returns:
            int
        """
        return getattr(self, self.get_shopify_fields()['id'])

    def _get_parent(self):
        """Returns parent object

        Returns:
            BaseShopify
        """
        if self.shopify_parent:
            return getattr(self, self.shopify_parent)

    def _iter_shopify_fields(self):
        for shopify_name, model_name in self.get_shopify_fields().items():
            yield shopify_name, getattr(self, model_name)

    def as_dict(self):
        """Returns Shopify resource attributes as dict

        Returns:
            dict
        """
        data = {}
        for name, value in self._iter_shopify_fields():
            if isinstance(value, Decimal):
                # Decimal is not JSON serializable, we need to convert it to string
                value = str(value)
            if isinstance(value, (datetime.date, datetime.datetime)):
                # Date/datetime is not JSON serializable, we need to convert it to string
                value = str(value)
            data[name] = value
        # Set parent ID
        if self.shopify_parent:
            data[self.shopify_parent_id_name] = self._get_parent().get_shopify_id()
        return data

    def as_shopify_resource(self):
        """Returns object as Shopify resource

        Returns:
            shopify.base.ShopifyResource
        """
        if self.shopify_resource_cls:
            return self.shopify_resource_cls(attributes=self.as_dict())

    @set_shopify_site
    def get_resource(self):
        """Hits Shopify API and gets the resource

        Returns:
            shopify.base.ShopifyResource
        """
        if self.get_shopify_id():
            return self.shopify_resource_cls.find(id_=self.get_shopify_id())

    def get_nested(self, name):
        # Get realted name
        related_name = self.shopify_fields_map.get(name, name)
        # Get nested queryset
        return getattr(self, related_name).all()

    def get_metafields(self):
        """
        Return Shopify resource metafields data as a list of dicts. Should be overridden in the child classes if needed

        Returns:
            list[dict]
        """
        return []

    def _set_metafields(self, resource):
        for item in self.get_metafields():
            item.update({'namespace': self.metafields_namespace})
            resource.add_metafield(Metafield(item))

    @set_shopify_site
    def sync(self, nested=True):
        """Syncs with Shopify and updates the instance

        Args:
            nested (bool): Sync nested objects (if exist)
        Returns:
            None
        Raise:
            base.exceptions.ShopifyApiError
        """
        resource = self.as_shopify_resource()

        # Don't update nested items from resource if it's a first time sync
        nested_resource = False
        if self.get_shopify_id():
            nested_resource = True

        if resource.save():
            self.update_from_resource(resource, nested=nested_resource)

            # Set metafields
            time.sleep(1)
            self._set_metafields(resource)

            if nested:
                for name in self.shopify_nested:
                    for obj in self.get_nested(name):
                        time.sleep(1)
                        obj.sync()

            return resource
        else:
            raise ShopifyApiError(
                f'Error saving {self.__class__.__name__} {self.pk}. {". ".join(resource.errors.full_messages())}'
            )

    @classmethod
    def from_json(cls, data, save=True, nested=True):
        """Creates instance from data came from Shopify API

        Args:
            data (dict):
            save (bool): save created instance; optional
            nested (bool): create neted objects too
        Returns:
            BaseShopify
        """
        instance = cls()
        instance.update(data, save=save, nested=nested)
        return instance

    def update_from_resource(self, resource, fields=None, save=True, nested=True):
        """Updates object from from Shopify resource

        Args:
            resource (shopify.base.ShopifyResource):
            fields (list): fields names which needs to be updated; optional
            save (bool): save updated instance; optional
            nested:
        Returns:
            None
        """
        self.update(resource.to_dict(), fields=fields, save=save, nested=nested)

    def update(self, data, fields=None, save=True, nested=True):
        """Updates object from data came from Shopify API

        Args:
            data (dict):
            fields (list): fields names which needs to be updated; optional
            save (bool): save updated instance; optional
            nested (bool): update nested objects too; these objects will be saved anyway
                ignoring the `save` & `fields` options; optional
        Returns:
            None
        """
        if not fields:
            # Get Shopify fields names list
            fields = self.get_shopify_fields().keys()

        for k in fields:
            if k in data:
                field = self.shopify_fields_map.get(k, k)
                setattr(self, field, data[k])

        if save:
            self.save()

        if nested:
            self.update_nested(data)

    def update_nested(self, data):
        """Updates/creates nested models from data came from Shopify API

        Args:
            data (dict):
        Returns:
            None
        """
        # Iterate nested types
        for nested in self.shopify_nested:
            # Get Shopify nested data
            _data = data.get(nested, [])
            related_name = self.shopify_fields_map.get(nested, nested)
            # Get nested queryset
            qs = getattr(self, related_name).all()
            model = qs.model
            model_shopify_id = model.get_shopify_fields()['id']

            # Iterate over Shopify nested objects
            for item in _data:
                if qs.filter(**{model_shopify_id: item['id']}).exists():
                    # If we found existing object update it
                    obj = qs.get(**{model_shopify_id: item['id']})
                    obj.update(item)
                else:
                    # Otherwise create new nested object
                    obj = model.from_json(item, save=False)
                    # Set parent object
                    setattr(obj, obj.shopify_parent, self)
                    obj.save()

    class Meta:
        abstract = True

steebie/base/views/api.py
from django.core.exceptions import ObjectDoesNotExist

from rest_framework.authentication import SessionAuthentication
from rest_framework.exceptions import NotFound
from rest_framework.parsers import JSONParser
from rest_framework.permissions import DjangoModelPermissions, IsAuthenticated
from rest_framework.views import APIView

from base.auth import IsMerchant


class BaseAPIResource(APIView):

    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated, DjangoModelPermissions, IsMerchant)
    parser_classes = (JSONParser,)
    model = None

    def get_queryset(self, **kwargs):
        return self.model.objects.filter(**kwargs)


class BaseAPIObjectResource(BaseAPIResource):

    def get_object(self, qs=None):
        if not qs:
            qs = self.get_queryset()
        try:
            return qs.get(pk=self.kwargs['pk'])
        except ObjectDoesNotExist:
            raise NotFound

steebie/templates/base.html
{% load static i18n compress %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}Steebie{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.bundle.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"
                integrity="sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"
                crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/48d5a4049a.js"></script>
        <script src="{% static 'js/main.js' %}"></script>

        <!-- Start of steebie Zendesk Widget script -->
        <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=84d46321-6b21-4ac4-bc34-606fd814b522"> </script>
        <!-- End of steebie Zendesk Widget script -->

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>

        <![endif]-->

        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i|Roboto:400,400i,700,700i"
              rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.4/cropper.css"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.css"/>
        <link rel="icon" href="{% static 'favicon.ico' %}">
        {% block css %}
            {% compress css %}
                <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
                <link href="{% static 'css/styles.css' %}" rel="stylesheet">
            {% endcompress %}
        {% endblock %}
        {% include 'inc/sentry.html' %}
    {% endblock head %}
</head>

<body>
    {% block body %}
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-light">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#headerNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Removing this section as we don't have active links
                <div class="collapse navbar-collapse nav-border-bottom" id="headerNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans "Who We Are" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans "Support" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans "Contact us" %}</a>
                        </li>
                    </ul>
                </div>

                TODO: Fix it in 1.2.1 -->

                <div class="d-flex col-12 mt-3 p-0 justify-content-between">
                    <div class="col text-center text-sm-left p-0">
                        <a class="navbar-brand" href="{% url 'app' %}">
                            <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="Steebie Logo"/>
                        </a>
                    </div>
                    <div class="d-none d-sm-block py-2 text-capitalize size-18">
                        {% if not user.is_anonymous and user.is_merchant %}
                            <a href="{% url 'app' %}#/campaign/create" class="btn btn-primary btn-lg rounded-lg ml-3 px-4 font-weight-bold">
                                {% trans 'New campaign' %}
                            </a>
                        {% endif %}
                    </div>
                    <div class="dropdown header-top">
                        <a class="dropdown-toggle nav-link" href="#" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">
                            {% if request.user.get_full_name %}
                                {{ request.user.get_full_name }}
                            {% else %}
                                {{ request.user.email }}
                            {% endif %}
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item nav-link" href="{% url 'users:account' %}">{% trans "Account" %}</a>
                            <a class="dropdown-item nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        {% block content %}{% endblock %}

        {% block footer %}{% endblock %}

        {% block javascript %}
        <!-- place project specific Javascript in this file -->
        {% compress js %}{% endcompress %}
        {% endblock javascript %}
    {% endblock body %}

    {% block bootstrap_form %}{% endblock bootstrap_form %}
    <div id="cover-spin"></div>
</body>
</html>